package com.hfad.gameoffaces;

import java.io.File;
import java.util.Dictionary;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Scanner;

public class ImageData {
    public static HashMap<String, Integer> Data() {
        HashMap<String, Integer> dictionary = new HashMap<String, Integer>();
        dictionary.put("Aady Pillai", R.drawable.aadypillai);
        dictionary.put("Aarushi Agrawal", R.drawable.aarushiagrawal);
        dictionary.put("Aayush Tyagi", R.drawable.aayushtyagi);
        dictionary.put("Abhinav Kejriwal", R.drawable.abhinavkejriwal);
        dictionary.put("Aditya Yadav", R.drawable.adityayadav);
        dictionary.put("Ajay Merchia", R.drawable.ajaymerchia);
        dictionary.put("Anand Chandra", R.drawable.anandchandra);
        dictionary.put("Andres Medrano", R.drawable.andresmedrano);
        dictionary.put("Andrew Santoso", R.drawable.andrewsantoso);
        dictionary.put("Angela Dong", R.drawable.angeladong);
        dictionary.put("Anika Bagga", R.drawable.anikabagga);
        dictionary.put("Anik Gupta", R.drawable.anikabagga);
        dictionary.put("Anita Shen", R.drawable.anitashen);
        dictionary.put("Anjali Thakrar", R.drawable.anjalithakrar);
        dictionary.put("Anmol Parande", R.drawable.anmolparande);
        dictionary.put("Ashwin Aggarwal", R.drawable.ashwinaggarwal);
        dictionary.put("Ashwin Kumar", R.drawable.ashwinkumar);
        dictionary.put("Athena Leong", R.drawable.athenaleong);
        dictionary.put("Austin Davis", R.drawable.austindavis);
        dictionary.put("Ayush Kumar", R.drawable.ayushkumar);
        dictionary.put("Brandon David", R.drawable.brandondavid);
        dictionary.put("Candace Chiang", R.drawable.candacechiang);
        dictionary.put("Candice Ye", R.drawable.candiceye);
        dictionary.put("Charles Yang", R.drawable.charlesyang);
        dictionary.put("Daniel Andrews", R.drawable.danielandrews);
        dictionary.put("Divya Tadimeti", R.drawable.divyatadimeti);
        dictionary.put("DoHyun Cheon", R.drawable.dohyuncheon);
        dictionary.put("Eric Kong", R.drawable.erickong);
        dictionary.put("Ethan Wong", R.drawable.ethanwong);
        dictionary.put("Imran Khaliq", R.drawable.imrankhaliq);
        dictionary.put("Izzie Lau", R.drawable.izzielau);
        dictionary.put("Jacqueline Zhang", R.drawable.jacquelinezhang);
        dictionary.put("Japjot Singh", R.drawable.japjotsingh);
        dictionary.put("Joey Hejna", R.drawable.joeyhejna);
        dictionary.put("Justin Kim", R.drawable.justinkim);
        dictionary.put("Kanyes Thaker", R.drawable.kanyesthaker);
        dictionary.put("Karen Alarcon", R.drawable.karenalarcon);
        dictionary.put("Katniss Lee", R.drawable.katnisslee);
        dictionary.put("Kayli Jiang", R.drawable.kaylijiang);
        dictionary.put("Kiana Go", R.drawable.kianago);
        dictionary.put("Leon Kwak", R.drawable.leonkwak);
        dictionary.put("Lewis Zhang", R.drawable.lewiszhang);
        dictionary.put("Matthew Locayo", R.drawable.matthewlocayo);
        dictionary.put("Max Emerling", R.drawable.maxemerling);
        dictionary.put("Max Miranda", R.drawable.maxmiranda);
        dictionary.put("Melanie Cooray", R.drawable.melaniecooray);
        dictionary.put("Michelle Mao", R.drawable.michellemao);
        dictionary.put("Mohit Katyal", R.drawable.mohitkatyal);
        dictionary.put("Mudabbir Khan", R.drawable.mudabbirkhan);
        dictionary.put("Natasha Wong", R.drawable.natashawong);
        dictionary.put("Neha Nagabothu", R.drawable.nehanagabothu);
        dictionary.put("Nikhar Arora", R.drawable.nikhararora);
        dictionary.put("Noah Pepper", R.drawable.noahpepper);
        dictionary.put("Patrick Yin", R.drawable.patrickyin);
        dictionary.put("Paul Shao", R.drawable.paulshao);
        dictionary.put("Radhika Dhomse", R.drawable.radhikadhomse);
        dictionary.put("Sai Yandapalli", R.drawable.saiyandapalli);
        dictionary.put("Salman Husain", R.drawable.salmanhusain);
        dictionary.put("Samantha Lee", R.drawable.samanthalee);
        dictionary.put("Shaina Chen", R.drawable.shainachen);
        dictionary.put("Sharie Wang", R.drawable.shariewang);
        dictionary.put("Shaurya Sanghvi", R.drawable.shauryasanghvi);
        dictionary.put("Shiv Kushwah", R.drawable.shivkushwah);
        dictionary.put("Shomil Jain", R.drawable.shomiljain);
        dictionary.put("Shubha Jagannatha", R.drawable.shubhajagannatha);
        dictionary.put("Shubham Gupta", R.drawable.shubhamgupta);
        dictionary.put("Sinjon Santos", R.drawable.sinjonsantos);
        dictionary.put("Srujay Korlakunta", R.drawable.srujaykorlakunta);
        dictionary.put("Stephen Jayakar", R.drawable.stephenjayakar);
        dictionary.put("Tyler Reinecke", R.drawable.tylerreinecke);
        dictionary.put("Vaibhav Gattani", R.drawable.vaibhavgattani);
        dictionary.put("Varun Jhunjhunwalla", R.drawable.varunjhunjhunwalla);
        dictionary.put("Victor Sun", R.drawable.victorsun);
        dictionary.put("Vidya Ravikumar", R.drawable.vidyaravikumar);
        dictionary.put("Vineeth Yeevani", R.drawable.vineethyeevani);
        dictionary.put("Will Oakley", R.drawable.willoakley);
        dictionary.put("Xin Yi Chen", R.drawable.xinyichen);
        return dictionary;
    }
}
